version: 2
jobs:
  test:
    environment:
      PY_ENV: test
      CC_TEST_REPORTER_ID: ff1651bfca53185e6d295b5989f89074b87fd7d68c6d1f938f19ea9186572a81

    working_directory: ~/SLM-Lab

    docker:
      - image: kengz/slm_lab:latest

    steps:
      - checkout
      - run:
          name: Install NodeJS dependencies
          command: |
            yarn install

      - run: echo '. ~/miniconda3/etc/profile.d/conda.sh' >> $BASH_ENV
      - run:
          name: Install Python dependencies with Conda
          command: |
            conda env update -f environment.yml

      - run:
          name: Run Python tests
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            conda activate lab
            python setup.py test
            ./cc-test-reporter after-build -d -p ~/SLM-Lab --exit-code $?
      - store_test_results:
          path: htmlcov

workflows:
  version: 2
  test:
    jobs:
      - test
